### ISSUE TITLE
[Request] Add support for nested blocks (aka plugins)

### ISSUE THREAD

**Issue by waldermort** [sonata-project/SonataBlockBundle#169]
First, I did notice that the default `Block` can have children and parents. Correct me if I'm wrong, but isn't that for persisting blocks to the database via the CMF bundle?

What I'm suggesting is a way for users to register a container block as a service, for example `SidebarService` and for that container to have associated children which are also services but registered with a different tag. The code would be something like this:

``` php
class PluginBlockService extends BaseBlockService
{
    public function __construct($name, EngineInterface $templating,$tagged)
    {
    }
}

class SidebarWhatsNewService extends BaseBlockService
{
}
```

``` yaml
services:
    acme.sidebar.container:
        class:              Acme\Bundle\Block\Service\SidebarBlockService
        arguments:
            - acme.sidebar.container
            - @templating
            - my.custom.sidebar.tag
        tags:
            - { name: sonata.block }
    acme.sidebar.widget:
        class:            Acme\Bundle\Block\Service\SidebarWhatsNewService
        tags:
            - { my.custom.sidebar.tag }
```

The container block should be added to the existing blocks (hence the name Plugin and not Container). This way users only need register the service(s) and optionally extend the base classes for finer control.

I have implemented this in my own project, and it works.

I had to create my own `WidgetLoader` tagged with `sonata.block.loader`. I then had to create a `CompilerPass` to scan for the custom tag and add to both `sonata.block.manager` and the c'tor of my `WidgetLoader`, which is then able to create and return the blocks. I can now render the sidebar without having to hardcode the content, And add/remove content blocks with ease.

I feel this should be in the core. Also, it can be implemented without breaking anything.
