### ISSUE TITLE
Cannot persist blocks [ConstraintViolationException]

### ISSUE THREAD

**Issue by bigfoot90** [sonata-project/SonataBlockBundle#178]
I'm trying persisting a StringBlock in my fixtures, but i have an exception while persisting the block.

Here is my `composer.lock`

``` yml
    ...
    "require": {
        "php":                                          ">=5.3.3",
        "twig/extensions":                              "~1.0",
        "symfony/symfony":                              "~2.4",
        "symfony/assetic-bundle":                       "~2.3",
        "symfony/monolog-bundle":                       "~2.4",
        "symfony/swiftmailer-bundle":                   "~2.3",
        "sensio/distribution-bundle":                   "~2.3",
        "sensio/framework-extra-bundle":                "~3.0",
        "stof/doctrine-extensions-bundle":              "~1.1",
        "incenteev/composer-parameter-handler":         "~2.0",

        "doctrine/orm":                                 "~2.4",
        "doctrine/mongodb":                             "~1.1",
        "doctrine/mongodb-odm":                         "1.0.*@dev",
        "doctrine/mongodb-odm-bundle":                  "3.0.*@dev",
        "doctrine/doctrine-bundle":                     "~1.2",
        "doctrine/phpcr-odm":                           "~1.2",
        "doctrine/phpcr-bundle":                        "~1.2",
        "doctrine/doctrine-cache-bundle":               "~1.0",
        "doctrine/doctrine-fixtures-bundle":            "~2.2",
        "jackalope/jackalope-doctrine-dbal":            "~1.1",

        "symfony-cmf/symfony-cmf":                      "~1.2",
        "symfony-cmf/routing-auto-bundle":              "~1.0",
        "symfony-cmf/block-bundle":                     "~1.2",
        "symfony-cmf/core-bundle":                      "~1.2",
        "symfony-cmf/seo-bundle":                       "~1.1",

        "sonata-project/block-bundle":                  "~2.2",
        "sonata-project/core-bundle":                   "~2.2",

        ...
    },
    ...
```

Here is my configuration

``` yml
cmf_core:
    persistence:
        phpcr:
            enabled:              true
            basepath:             /cms
            manager_registry:     doctrine_phpcr

cmf_routing:
    chain:
        routers_by_id:
            router.default: 100
            cmf_routing.dynamic_router: 200

    dynamic:
        persistence:
            phpcr:
                route_basepath: /cms/routes
                content_basepath: /cms/pages
        generic_controller: sv.public.controller.default:pageAction
        controllers_by_class:
            Symfony\Cmf\Component\Routing\RedirectRouteInterface: cmf_routing.redirect_controller:redirectAction

cmf_block:
    persistence:
        phpcr:
            block_basepath: /cms/content
```

Here is my fixture class

``` php
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock;
use Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\StringBlock;
use Symfony\Component\DependencyInjection\ContainerAware;

class LoadBlocks extends ContainerAware implements FixtureInterface
{
    private $root_block;

    /**
     * Load data fixtures with the passed EntityManager
     *
     * @param ObjectManager $manager
     */
    public function load(ObjectManager $manager)
    {
        $this->root_block = $manager->find(null, $this->container->getParameter('cmf_block.persistence.phpcr.block_basepath'));
        $block = new StringBlock();
        $block->setParentDocument($this->root_block);
        $block->setName('Footer');
        $block->setType('footer');
        $block->setBody(<<<CONTENT
Some example content
CONTENT
        );

        $manager->persist($block);
        $manager->flush();
}
```

I'm having 

```
  [PHPCR\NodeType\ConstraintViolationException]       
  Can't remove the protected property: jcr:createdBy 
```

Any idea?
