### ISSUE TITLE
[Question] How to activate diffrent blocks for different sections

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataBlockBundle#189]
Hi!

I have the following config:

````
   templates:
        default:
            path: 'AppBundle::layout.html.twig'
            name: 'DEFAULT-Design'
            containers:
                header:
                    name:   Header
                content_fullwidth:
                    name:   Full width content (stage)
                content_narrow:
                    name:   Narrow content (with sidebar)
                sidebar:
                    name:   Sidebar
                    blocks:
                        - exozet.block.service.contact_block
                        - exozet.block.service.side.navigation
                        - exozet.block.service.stock_price_block
                content:
                    name:   Content
                footer:
                    name:   Footer
            matrix:
                layout: |
                    HHHHHHHH
                    HHHHHHHH
                    WWWWWWWW
                    WWWWWWWW
                    NNNNNSSS
                    NNNNNSSS
                    NNNNNSSS
                    CCCCCCCC
                    CCCCCCCC
                    CCCCCCCC
                    FFFFFFFF
                    FFFFFFFF

                mapping:
                    H: header
                    W: content_fullwidth
                    N: content_narrow
                    S: sidebar
                    C: content
                    F: footer
```` 
the user should only have these blocks:
````
                    blocks:
                        - exozet.block.service.contact_block
                        - exozet.block.service.side.navigation
                        - exozet.block.service.stock_price_block
````
available in the sidebar!

but i think i'am using this config wrong

best regards

oskar
