### ISSUE TITLE
Sonata admin block url route

### ISSUE THREAD

**Issue by gnorby88** [sonata-project/SonataBlockBundle#220]
This is possible? Rss block with route?

```
                type: sonata.block.service.rss
                settings:
                    title: Latests orders
                    url: admin_app_order_feedLatestOrders
```

instead of full url..
