### ISSUE TITLE
Custom block throwing exception after update to newest version (3.0)

### ISSUE THREAD

**Issue by buelsenfrucht** [sonata-project/SonataBlockBundle#278]
Hi guys,

I had to update sonata-admin to 3.0 the other day, which forced me to update user and block bundle too.
Now I'm getting an error when opening the dashboard with a custom block.

I created a block which will be used for an omnisearch in the future.
This block worked fine when I was on the sonata-admin 2.4 development branch.

Can please tell me someone what changed since then and how I can fix it?
Why is template empty although I set it in setDefaultSettings?
# Error message

```
An exception has been thrown during the rendering of a template 
("Unable to find template "" (looked into: /var/www/retailer-internal/app/Resources/views, /var/www/retailer-internal/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form, /var/www/retailer-internal/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views).") 
in AppBundle::dashboard.html.twig at line 98.
```
# Steps to reproduce
## Service class

``` php
class SearchBlockService extends BaseBlockService implements BlockServiceInterface
{
    /**
     * {@inheritdoc}
     */
    public function setDefaultSettings(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'url'      => false,
            'title'    => 'Omnisearch',
            'template' => 'AppBundle:Block:block_search.html.twig',
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return "Omnisearch";
    }


    /**
     * {@inheritdoc}
     */
    public function execute(BlockContextInterface $blockContext, Response $response = null)
    {
        return $this->renderResponse($blockContext->getTemplate(), array(
            'block'     => $blockContext->getBlock(),
            'settings'  => $blockContext->getSettings()
        ), $response);
    }

}
```
## View (under `Resources/views/Block/block_search.html.twig`)

``` twig
{% extends 'SonataBlockBundle:Block:block_base.html.twig' %}

{% block block %}
    <div class="row">
        <div class="col-lg-12">
            <div class="input-group col-lg-12">
                <input type="text" name="q" id="q" class="form-control input-lg" placeholder="Suchbegriff (E-Mailadresse, Bestellnummer etc.)">
                    <span class="input-group-btn">
                        <button class="btn btn-default btn-lg btn-primary" type="submit" id="submitButton" data-loading-text="Suche..." autocomplete="false">Los!</button>
                    </span>
            </div>
        </div>
    </div>
{% endblock %}
```
## services.yml

``` yaml
services:
    sonata.block.service.search:
        class: AppBundle\Block\SearchBlockService
        arguments: [ sonata.block.service.search, "@templating" ]
        tags:
            - { name: sonata.block }
```
## config.yml

``` yaml
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        sonata.block.service.search: ~

...

sonata_admin:
    templates:
        layout: AppBundle::standard_layout.html.twig
        list: AppBundle::list.html.twig
        dashboard: AppBundle::dashboard.html.twig
    dashboard:
        blocks:
            - { position: center, type: 'sonata.block.service.search' }

```
