### ISSUE TITLE
Blocks as service seem uncachable

### ISSUE THREAD

**Issue by dinhkhanh** [sonata-project/SonataBlockBundle#329]
I create a menu block like this.

``` yml
#/app/config/config.yml
sonata_cache:
    caches:
        predis:
            servers:
                - {host: 127.0.0.1, port: 6379, database: 0}
sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.block.service.menu:
            cache: sonata.cache.predis
```

``` twig
{#index.html.twig #}
{{ sonata_block_render({
    'type': 'sonata.block.service.menu',
    'settings':
    {
        'menu_name': 'main'
    }
}) }}
```

Blocks Profiler

| Block | 57aaf17ce403e |
| --- | --- |
| Type | sonata.block.service.menu |
| Mem. diff / Mem. peak / Duration | 0 Kb / 2,097 Kb / 25.00 ms |
| Cache backend | sonata.cache.predis - Loading from cache: NO |
| Cache TTL / Lifetime | 86400s. / 86400s |
| Cache Informations | Cache Keys {"block_id":"57aaf17ce403e","updated_at":"1470820732","context":{"menu_name":"main"}} . Contextual Keys: {"Sonata\BlockBundle\Model\Block":["57aaf17ce403e"]} |

And this is what it looks like in Redis database:
# 96a28ffd1f71f5641e115d4b15f18ce4

| Field | Value |
| --- | --- |
| updated_at | 1470820522 |
| sonata__data | O:25:"Sonata\Cache\CacheElement":5:{s:6:"_ttl";i:86400;s:7:"_.... |
| block_id | 57aaf0aa9cb3e |
| Sonata\BlockBundle\Model\Block | a:1:{i:0;s:13:"57aaf0aa9cb3e";} |
| context | a:2{s:9:"menu_name";s:4:"main";} |

Everytime I reload the page, it creates a brand new hash key in Redis database.

Does I miss something in configuration? How to make a block cachable?
