### ISSUE TITLE
With Update to 3.3 blocks are broken

### ISSUE THREAD

**Issue by wodka** [sonata-project/SonataBlockBundle#374]
## Subject

the following error is thrown:

```
ContextErrorException in TweakCompilerPass.php line 44:
Notice: Undefined offset: 0
```

the loop for the service ids has an empty argument.

```
$id = string 'admin.block.stat.count' (length=22)
$arguments =array (size=0)  empty
```

## service definition

is done through annotations:

```php
/**
 * @DI\Service("admin.block.stat.count")
 * @DI\Tag("sonata.block")
 */
class StatCountBlock extends AbstractBlockService
```

**Comment by wodka** [comment]
ah - the arguments were not required in 3.2

and I cannot set those through annotations so that the TweakCompilerPass can pick them up. I moved the configuration to yaml and it's working then.

**Comment by artursvonda** [comment]
`setArgument` is not available on Symfony 2.8 and throws error

**Comment by greg0ire** [comment]
@artursvonda can you please make a PR to fix this?

**Comment by artursvonda** [comment]
I can take shot at it but probably only next week

**Comment by artursvonda** [comment]
By the way, temporary workaround is to set first argument explicitly to be the same as service name.

**Comment by romaricdrigon** [comment]
I also got this issue with Sonata 3.43 & Symfony 2.8.
In my case, @artursvonda did not worked - the issues was that I was using named arguments. removing those worked:
```yaml
    # broken
    sonata.block.acme:
        class: App\SonataBundle\Block\AcmeBlockService
        arguments:
            type: "sonata.block.service.text"
            templating: "@templating"
            searcher: "@admin.search"
            em: "@doctrine.orm.entity_manager"
        tags:
            - { name: sonata.block }

    # fixed
    sonata.block.acme:
        class: App\SonataBundle\Block\AcmeBlockService
        arguments:
            - "sonata.block.service.text"
            - "@templating"
            - "@admin.search"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: sonata.block }
```

I hope it can help anyone stuck on old versions :)
