### ISSUE TITLE
Cannot set block cache expire ttl parameter

### ISSUE THREAD

**Issue by dkorsak** [sonata-project/SonataBlockBundle#75]
I would like to set cache expire parameter ttl.
First method by config.yml:

``` yaml
my_block_id:
    cache: sonata.cache.memcached
    settings: {ttl: 60}
```

Second method:

``` php
public function setDefaultSettings(OptionsResolverInterface $resolver)
{
    $resolver->setDefaults(array('ttl' => 60));
}
```

Both methods donot work. Ttl is always set to default value 84600.
