### ISSUE TITLE
Attempting to create a new block

### ISSUE THREAD

**Issue by gavinwilliams** [sonata-project/SonataBlockBundle#8]
I'm trying to create a new block. However everytime I do I always recieve an error stating that the block service doesn't exist if I attempt to add it directly to the twig template.

Has anybody else experienced this problem. I'm basically attempting to create a KnpMenu block...

FYI. I get the following error in the logs.

request.CRITICAL: RuntimeException: The block service `application.sonata.block.service.menu` does not exists (uncaught exception) at /vagrant/vendor/bundles/Sonata/BlockBundle/Block/BlockServiceManager.php line 47 [] []

Despite having the following in my services configuration

``` xml
        <service id="application.sonata.block.service.menu" class="Application\Sonata\BlockBundle\Block\MenuBlockService">

            <tag name="sonata.block" />
            <argument>application.sonata.block.service.menu</argument>
            <argument type="service" id="templating" />

        </service>
```

And the following in my configuration yml file.

``` yaml
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        application.sonata.block.service.menu:
    default_contexts: [cms]
```
